### ISSUE TITLE
[question] Is it safe to call this library multiple times

### ISSUE THREAD

**Issue by newbeelearn** [modfin/pg-xid#1]
I see that it is setting xid_serial with setval which will override previous value is that ok or care needs to be taken to ensure that it is only initialized once?

**Comment by crholm** [comment]
Hi. Why would you run it multiple times? 

In general

The first line
```CREATE DOMAIN public.xid AS CHAR(20) CHECK (VALUE ~ '^[a-v0-9]{20}$');```
Will fail, if i'm not mistaken, since `public.xid` already will exist the second time around.

The line
```SELECT setval('xid_serial', (random() * 16777215)::INT); --  ((255<<16) + (255<<8) + 255))```
Is in accordance to the spec where a random number is suppose to be used for a seed. Calling it again will result in a new value of `xid_serial`, but this might not matter to much dependent on your use-case. But running it multiple times a second will definitely cause problems and conflicting xids are much more likely regardless if the sequence are not allowed to progress

**Comment by newbeelearn** [comment]
thanks for the quick reply and clear explanation.
