### ISSUE TITLE
Performance Question

### ISSUE THREAD

**Issue by denys0504** [modfin/pg-xid#9]
First of all, thank you for your awesome work for `xid`.

I guess using `CHAR(20)` will perform slowly in terms of sorting and indexing compared to using `UUID` type and have some questions here.

- Is this okay to use in production-level apps?  (In terms of performance)
- Would it perform better when we use raw byte data type instead of `CHAR(20)` in terms of sorting, and indexing?

**Comment by denys0504** [comment]
Update:  I think `CHAR(20)` is better because it's hard to see in database browser if we use something like `bytea`
Hope postgresql natively supports this later.

**Comment by crholm** [comment]
Well, performance hasn't been the main priority I porting xid to pgsql.

In general I would say it is has much worse performance than most uuid equivalent functions and operations, simply because uuid is an extension running in c while xid runs as a script. 

I wouldn't suggest you bench it's performance in terms of what you need for use case
